### PR TITLE
add handle() method to Window and RenderWindow

### PR DESCRIPTION
**Pull request by silverweed**
This PR adds the ability to retrieve the SystemHandle from Window and RenderWindow.

### CODE REVIEW

**Comment by crumblingstatue** [comment]
Looks good, but can you refer to `Handle` in the documentation instead of `sf::WindowHandle`?

**Comment by crumblingstatue** [comment]
Also, maybe system_handle might be a better name for the method? It would be closer to the original `getSystemHandle` name.

**Comment by silverweed** [comment]
Done!

**Comment by crumblingstatue** [comment]
Thanks for your contribution!

**Pull request merged**
