### PR TITLE
[WIP] Alternate implementation of SoundRecorder

### PR DESCRIPTION
**Pull request by crumblingstatue**
Alternative to #171

### CODE REVIEW

**Comment by petoknm** [comment]
We wantz dis. [Plz merge](https://media.giphy.com/media/R6nV6C5uC16Fy/giphy.gif)

**Comment by crumblingstatue** [comment]
I wanted an example that instantly plays back what's being recorder, but the current API actually makes it impossible.

I'll think about this tomorrow.

**Comment by petoknm** [comment]
It should be possible if we hook up a buffer inbetween the sound recorder and the sound player.

**Comment by crumblingstatue** [comment]
I'll merge this into master, we can work on further refining the design later.

**Pull request merged**
