### PR TITLE
Add input stream functionality

### PR DESCRIPTION
**Pull request by boghison**

### CODE REVIEW

**Comment by boghison** [comment]
Oops, I only added a create function for music. Please do not merge yet.

**Comment by boghison** [comment]
OK, it's fine now :)

**Comment by jeremyletang** [comment]
Hey @boghison, thanks for the pull request, I will check this soon !

**Comment by jeremyletang** [comment]
Can you add an simple example where you use the input stream please ? For example you load a font using a stream, then you draw a text in an empty window to check this is working ?

**Comment by boghison** [comment]
@jeremyletang I only checked audio. I edited the test function and instead of loading from a filename, I created a rust File (which implements Read + Seek) and loaded it into create_from_stream. Hope that helps :3

**Comment by boghison** [comment]
@jeremyletang I just edited pong.rs. It works awesomely :D

**Comment by jeremyletang** [comment]
hum, okay great can you push your change ? or create a example file just to show peoples how works input stream (this will be really great !).
Thanks !

**Comment by boghison** [comment]
@jeremyletang Umm, okay. Should I just create something like audio_stream.rs (to show how audio works with inputstream)?

**Comment by jeremyletang** [comment]
Yes exactly !

**Comment by boghison** [comment]
@jeremyletang Okay, done.

**Comment by boghison** [comment]
Bump.

**Comment by jeremyletang** [comment]
Hey this, seems okay, just a last question, you doesn't implement the input_stream constructor for textures. Any reason for this ?

**Comment by boghison** [comment]
@jeremyletang Because of "sfIntRect", but if that is the same as IntRect I'll add it as well

**Comment by boghison** [comment]
Should I also update Cargo.toml? (The version?)

**Comment by jeremyletang** [comment]
@boghison Yes, sfIntRect and Intrect are the same, you just need to replace sfIntRect with IntRect in the prototype.
Yes, you can increment the version to 0.9.4 in the cargo.toml.

**Comment by jeremyletang** [comment]
Thanks @boghison, it works well ! Great job !

**Pull request merged**
