### PR TITLE
Build & Repo Enhancements

### PR DESCRIPTION
**Pull request by eriknelson**
- Add optional LDFLAGS to build to support custom installation location
  of SFML/CSFML dependent libraries.

- rm build products on clean

- Ignore build products in .gitignore

### CODE REVIEW

**Comment by eriknelson** [comment]
Looks like the build failure is due to the recent nightly, I'm on the following nightly with no issue:
rustc: 39d740266 2015-01-01
cargo: 1a1868b 2014-12-31

**Comment by eriknelson** [comment]
Addresses #67

**Comment by jeremyletang** [comment]
Hey, thanks for the changes !

Do you use the makefile to build rsfml ? I've let it in the repo when I switched to cargo, but I planned to remove it soon.

**Comment by erik-sb** [comment]
Hey Jeremy,

I think this should cover both the cargo build and the make build. Personally, I prefer to use cargo if possible since it's becoming more idiomatic in the rust ecosystem. The motivation behind this was because the distro I'm using did not package the required C/SFML libs. I had to build them from source, which I prefer to make install to a non-sudo prefix location to isolate them from the package manager installed libs.

**Comment by eriknelson** [comment]
Hey Jeremy,

I think this should cover both the cargo build and the make build. Personally, I prefer to use cargo if possible since it's becoming more idiomatic in the rust ecosystem. The motivation behind this was because the distro I'm using did not package the required C/SFML libs. I had to build them from source, which I prefer to make install to a non-sudo prefix location to isolate them from the package manager installed libs.

**Comment by Syntaf** [comment]
Is there any movement towards getting this merged? [ref](http://stackoverflow.com/questions/31630064/rust-sfml-linking-with-cc-failed-how-to-specify-lib-include-share-path/31630169#31630169)

**Pull request closed without merging**
