### PR TITLE
Make Drawable::draw callable on trait objects

### PR DESCRIPTION
**Pull request by emlai**
Now you can f.ex. store a `Vec` of `Drawable`s (trait objects), loop
through them and call `draw` on each of them.

More information about this issue:
http://stackoverflow.com/q/32081065/3425536

### CODE REVIEW

**Comment by emlai** [comment]
Fixing build…

**Comment by crumblingstatue** [comment]
This replaces static dispatch by dynamic dispatch, I'm not sure what @jeremyletang would think about this, so I'll wait for him to review it.

**Comment by jeremyletang** [comment]
Hey,
I'm a bit annoyed with replacing static dispatch with dynamic dispatch, I don't know the runtime cost on a collection of a lot of objects.
Is it possible to add the method to the trait and keep the existing one and keep the object safe using this method ? Or all the methods should respect objects safety rules ?

**Comment by emlai** [comment]
> Is it possible to add the method to the trait and keep the existing one and keep the object safe using this method ? Or all the methods should respect objects safety rules ?

I have no idea, unfortunately.

If you think static dispatch is better in this case then you can close this PR, as far as I'm concerned.

**Comment by crumblingstatue** [comment]
We will probably want to decide whether to support dynamic dispatch or not before 1.0.

**Comment by crumblingstatue** [comment]
We might want to consider supporting this, because the C++ SFML API also supports dynamic dispatch of `RenderTarget`.

**Comment by crumblingstatue** [comment]
Closing in favor of #149.

**Pull request closed without merging**
